format = """
[░▒▓](#1d2230)\
$directory\
$git_branch\
$git_status\

$nodejs\
$rust\
$golang\
$php\
[▓▒░](#1d2230)\

$fill\
[░▒▓](#1d2230)\
$username\
[](fg:#1d2230 bg:#1d2230)\
$shell\
[](fg:#1d2230 bg:#1d2230)\
$os\
[](bg:#1d2230 fg:#1d2230)\
$time\
[▓▒░](#1d2230)\
\n$character
"""
right_format = """
"""

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
symbol = "󰏗 "

[directory]
style = "fg:#090c0c bg:#74778C"
format = "[](bg:#1d2230 fg:#74778C)[ $path ]($style)[](bg:#1d2230 fg:#74778C)"
truncation_length = 3
truncation_symbol = "…/"
read_only = " 󰌾"



[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = "\ue0a0"
style = "bg:#1d2230"
format = '[ ](bg:#1d2230 fg:#859FC8)[[ $symbol $branch ](fg:#090c0c bg:#859FC8)]($style)'

[git_status]
style = "bg:#74778C"
format = '[[($all_status$ahead_behind )](fg:#090c0c bg:#859FC8)]($style)[](fg:#859FC8 bg:#1d2230)'

[git_commit]
commit_hash_length=4
tag_symbol="\uf417"

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[ ](fg:#89B8C1 bg:#1d2230)[[ $symbol ($version) ](fg:#090c0c bg:#89B8C1)]($style)[ ](bg:#1d2230 fg:#89B8C1)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[ ](fg:#89B8C1 bg:#1d2230)[[ $symbol ($version) ](fg:#090c0c bg:#89B8C1)]($style)[ ](bg:#1d2230 fg:#89B8C1)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[ ](fg:#89B8C1 bg:#1d2230)[[ $symbol ($version) ](fg:#090c0c bg:#89B8C1)]($style)[ ](bg:#1d2230 fg:#89B8C1)'

[php]
symbol = ""
style = "bg:#212736"
format = '[ ](fg:#89B8C1 bg:#1d2230)[[ $symbol ($version) ](fg:#090c0c bg:#89B8C1)]($style)[ ](bg:#1d2230 fg:#89B8C1)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'


[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "


[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fossil_branch]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[os]
format = "[ $symbol](bg:#1d2230 fg:#090c0c)"
disabled = false

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[scala]
symbol = " "

[username]
style_user = '#a3aed2 bold'
style_root = '#090c0c bold'
format = '[ $user](bg:#1d2230 fg:#090c0c)($style)'
disabled = false
show_always = true

[shell]
fish_indicator = '󰈺 '
bash_indicator = "\uebca "
zsh_indicator = 'Z'
powershell_indicator = '_'
unknown_indicator = 'mystery shell'
style = 'cyan bold'
disabled = false
format = '[ $indicator](bg:#1d2230 fg:#090c0c)'

[fill]
symbol = ' '
